language: node_js
node_js:
- '8'
env:
- NODE_ENV=development
services:
- mongodb
script:
- npm test
after_success:
- npm run coveralls
addons:
  ssh_known_hosts: "api.opencloudschool.org"
before_install:
- openssl aes-256-cbc -K $encrypted_fadb6885fa4a_key -iv $encrypted_fadb6885fa4a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: git push ssh://$PRODUCTION_SERVER_USER@$PRODUCTION_SERVER:$DIR_PATH HEAD:master
  on:
    branch: master
